set(Plugin-Name "Common Application Level Features")
set(Plugin-Version "0.1")
set(Plugin-Vendor "CMIC, Centre For Medical Image Computing, UCL.")
set(Plugin-ContactAddress "http://cmic.cs.ucl.ac.uk/")
set(Require-Plugin org.mitk.core.ext org.mitk.gui.qt.application)
