set(PROJECT_PLUGINS
  Plugins/uk.ac.ucl.cmic.midasgeneralsegmentor:ON
  Plugins/uk.ac.ucl.cmic.niftyreg:OFF
  Plugins/uk.ac.ucl.cmic.niftyseg:OFF
  Plugins/uk.ac.ucl.cmic.gui.qt.common:ON
  Plugins/uk.ac.ucl.cmic.gui.qt.niftyview:ON
  Plugins/uk.ac.ucl.cmic.imagelookuptables:ON
  Plugins/uk.ac.ucl.cmic.midasmorphologicalsegmentor:ON
  Plugins/uk.ac.ucl.cmic.affinetransform:ON
  Plugins/uk.ac.ucl.cmic.thumbnail:ON
  Plugins/uk.ac.ucl.cmic.midasnavigation:ON
  Plugins/uk.ac.ucl.cmic.snapshot:ON
  Plugins/uk.ac.ucl.cmic.surgicalguidance:ON
)
