#if !defined(XNATRESTSTATUS_H)
#define XNATRESTSTATUS_H

enum XnatRestStatusCodes
{
  XNATREST_OK,        /* returned when XnatRest function is successful */
  XNATREST_NOMEM,
  XNATREST_NOGLOBAL,
  XNATREST_NOHANDLE,
  XNATREST_NOMULTIHANDLE,
  XNATREST_USERPWDERR,
  XNATREST_NOGET,
  XNATREST_NOPUT,
  XNATREST_NODELETE,
  XNATREST_NORESTURI,
  XNATREST_NOCONNECT,
  XNATREST_NOAUTH,
  XNATREST_BADQUERY,
  XNATREST_HTTPERROR,
  XNATREST_CURLERROR,
  XNATREST_CURLMULTIERROR,
  XNATREST_ASYNINPROGRESS,
  XNATREST_NOASYNINPROGRESS,
  XNATREST_MISSINGNODE,
  XNATREST_MISSINGPATH,
  XNATREST_ERROR,
  XNATREST_IOERROR,
  XNATREST_COL_OVERFLOW,
  XNATREST_CSV_NOQUOTE,
  XNATREST_CSV_INVALID,
  XNATREST_CSV_NOCOL,
  XNATREST_CSV_BADCOL,
  XNATREST_CSV_NOMEM,
  XNATREST_CB_OVERFLOW,
  XNATREST_CB_ERROR,
  XNATREST_UNZ_NOZIPNAME,
  XNATREST_UNZ_ZIPOPENERR,
  XNATREST_UNZ_GBLINFOERR,
  XNATREST_UNZ_NXTFILEERR,
  XNATREST_UNZ_CURINFOERR,
  XNATREST_UNZ_CUROPENERR,
  XNATREST_UNZ_CURREADERR,
  XNATREST_UNZ_CURCLOSERR,
  XNATREST_UNZ_OUTOPENERR,
  XNATREST_UNZ_OUTWRITERR,
  XNATREST_UNZ_BADOUTDIR,
  XNATREST_UNZ_MKDIRERR,
  XNATREST_UNZ_NOMEM,
  XNATREST_ZIP_ZIPOPENERR,
  XNATREST_ZIP_CUROPENERR,
  XNATREST_ZIP_CURWRITERR_LTZ,
  XNATREST_ZIP_CURWRITERR_GTZ,
  XNATREST_ZIP_CURCLOSERR,
  XNATREST_ZIP_INOPENERR,
  XNATREST_ZIP_INREADERR,
  XNATREST_ZIP_NOMEM,
  XNATREST_WSASTARTUPERR,
  XNATREST_NOT_PYSEQUENCE,
  XNATREST_END         /* end of enumerated status codes */
};

typedef enum XnatRestStatusCodes XnatRestStatus;

#endif
