set(Plugin-Name "CMIC Breast Segmentation")
set(Plugin-Version "0.1")
set(Plugin-Vendor "CMIC, Centre For Medical Image Computing, UCL.")
set(Plugin-ContactAddress "")
set(Require-Plugin org.mitk.gui.qt.common)
