set(Plugin-Name "CIM Core")
set(Plugin-Version "0.1")
set(Plugin-Vendor "CIM Unito")
set(Plugin-ContactAddress "http://www.cim.unito.it")
set(Require-Plugin org.mitk.gui.qt.common org.mitk.gui.qt.datamanager)
set(Plugin-ActivationPolicy eager)
